- name: Install bash completion
  apt:
    name: "bash-completion"
    state: present
    update_cache: yes

- name: Install vim
  apt:
    name: vim
    state: present
    update_cache: yes

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

