- name: Install HAProxy
  apt: 
    name: haproxy
    state: present
    update_cache: yes
  notify:
    - haproxy status

- name: Create HAProxy config from template
  template:
    src: ../templates/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted

