- name: Switch nftables to iptables
  shell:
    cmd: "{{ item }}"
  loop:
    - update-alternatives --set iptables /usr/sbin/iptables-legacy
    - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
