- name: Install MetalLB
  become: false
  command: "{{ item }}"
  with_items:
   - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
   - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
   - kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

- name: create MetalLB config
  become: false
  copy:
    dest: /tmp/metallb-config.yaml
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - {{ metallb_addresses }}

- name: install MetalLB config
  become: false
  command: kubectl create -f /tmp/metallb-config.yaml
